config/routes.rb
Rails.application.routes.draw do
  resources :compras
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'compra#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:fecha, :monto, :cliente)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/scaffolds_helper.rb
module ScaffoldsHelper
end

app/views/compras/_form.html.erb
<%= form_with(model: compra, local: true) do |form| %>
  <% if compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :compra_fecha,
    class: 'large-12 columns'%>
  </div>

  <div class="field">
    <%= form.label :monto %>
    <%= form.number_field :monto, id: :compra_monto,
    title:'Precio'%>
  </div>

  <div class="field">
    <%= form.label :cliente %>
    <%= form.text_area :cliente, id: :compra_cliente,
    title:'Tu nombre', data:{tooltip: true}%>
  </div>

  <div class="actions">
    <%= form.submit class:'button success'%>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Show', @compra ,
class: 'button secondary'%> |
<%= link_to 'Back', compras_path,
class: 'button secondary alert'%>

app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compras</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Monto</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.fecha %></td>
        <td><%= compra.monto %></td>
        <td><%= compra.cliente %></td>
        <td><%= link_to 'Show', compra,
        class: 'button radius'%></td>
        <td><%= link_to 'Edit', edit_compra_path(compra),
         class:'button radius success'%></td>
        <td><%= link_to 'Destroy', compra, method: :delete, data: { confirm: 'Are you sure?' },
        class: 'button radius alert'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compra', new_compra_path,
class: 'button expand'%>

app/views/compras/new.html.erb
<h1>New Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Back', compras_path,
class:'button primary'%>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @compra.fecha %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @compra.monto %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @compra.cliente %>
</p>

<%= link_to 'Edit', edit_compra_path(@compra),
class: 'button primary'%> |
<%= link_to 'Back', compras_path,
class: 'button radius success'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Scaffold</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

    <%= yield %>

  </body>
</html>